### ISSUE TITLE
SetupTexture

### ISSUE THREAD

**Issue by sasasuta** [ICAMS/Kanapy#22]
when i try matlab R2017b and run "kanapy setupTexture", some errors occur:

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/shen/MATLAB/R2017b/extern/engines/python/setup.py", line 13, in <module>
          raise EnvironmentError('MATLAB Engine for Python supports Python version'
      OSError: MATLAB Engine for Python supports Python version 2.7, 3.4, 3.5 and 3.6 but your version of Python is 3.8
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "init_engine.py", line 9, in <module>
    import matlab.engine
ModuleNotFoundError: No module named 'matlab'

_Originally posted by @sasasuta in https://github.com/ICAMS/Kanapy/issues/21#issuecomment-1585727205_

**Comment by AHartmaier** [comment]
The installation scripts have been tested for Matlab R2023a with Python 3.9.16. If you are using other Matlab versions, the script "setupTexture" might fail. In this case, you can setup the Matlab Engine API for Python manually. To do so, please follow the instructions given on the Mathworks website (https://de.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html), to (i) Verify your configuration, (ii) Install Engine API, and (iii) Start MATLAB Engine. The Python version of the *knpy*-environment can be changed according to the requirements of the Matlab Engine API by editing the "environment.yml" file and re-creating the conda environment *knpy*.
If the texture module (tes_texture.py) fails the test, the cause lies oftentimes in a wrong MATLAB path. Please run "$ matlab startup_mtex.m" in that case to fix the problem.

**Comment by AHartmaier** [comment]
Hello sasasuta,

I recommend to update your Matlab version because in the previous versions the support for the Matlab Engine API for Python was rather limited. If it is not possible for your to upgrade Matlab, you will need to downgrade your Python version by editing the „environment.yml“ file and setting up a new conda environment. The highest Python version supported by Matlab R2017b is Python 3.6

The installation scripts have been tested for Matlab R2023a with Python 3.9.16. If you are using other Matlab versions, the script "setupTexture" might fail. In this case, you can setup the Matlab Engine API for Python manually. To do so, please follow the instructions given on the Mathworks website (https://de.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html), to (i) Verify your configuration, (ii) Install Engine API, and (iii) Start MATLAB Engine. The Python version of the *knpy*-environment can be changed according to the requirements of the Matlab Engine API by editing the "environment.yml" file and re-creating the conda environment *knpy*.

If the texture module (test_texture.py) fails the test, the cause lies oftentimes in a wrong MATLAB path. Please run "$ matlab startup_mtex.m" in that case to fix the problem.

Please contact me directly under this email address if your problem persists. I will be happy to assist you and to make kanapy work on your system.

Best wishes
Alexander

--
Dr. Alexander Hartmaier
Professor and Director
Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
Ruhr-Universität Bochum
44780 Bochum
Germany

Phone: +49 234 32-29314
Mobile: +49 160 5875012
Email: ***@***.******@***.***>
Web: http://www.icams.rub.de



Am 10.06.2023 um 18:32 schrieb sasasuta ***@***.******@***.***>>:



when i try matlab R2017b and run "kanapy setupTexture", some errors occur:

Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/home/shen/MATLAB/R2017b/extern/engines/python/setup.py", line 13, in
raise EnvironmentError('MATLAB Engine for Python supports Python version'
OSError: MATLAB Engine for Python supports Python version 2.7, 3.4, 3.5 and 3.6 but your version of Python is 3.8
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
File "init_engine.py", line 9, in
import matlab.engine
ModuleNotFoundError: No module named 'matlab'

Originally posted by @sasasuta<https://github.com/sasasuta> in #21 (comment)<https://github.com/ICAMS/Kanapy/issues/21#issuecomment-1585727205>
