### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by AHartmaier** [ICAMS/Kanapy#5]
Progress bar does not display well in Spyder or Juypter notebooks. Are there options to cure this?

**Comment by srmnitc** [comment]
Using `from tqdm.notebook import tqdm`, instead of `from tqdm import tqdm` can render the progress bar in a better way in notebooks. Please see [here](https://tqdm.github.io/docs/notebook/). Alternatively, the package rich also provides a [good progress bar](https://rich.readthedocs.io/en/stable/progress.html).
